# go-zero config
Name: GameX
Mode: dev

Log:
  ServiceName: usercenter-rpc
  Level: info

Redis:
  Host: redis:6379
  Type: node
  Pass: G62m50oigInC30sf
  Key: usercenter-rpc
  NonBlock: false

# zinx config
ZinxConf:
  Name: GameX
  Host: 0.0.0.0
  WsPort: 9000
  MaxPacketSize: 4096
  MaxConn: 1
  MaxWorkerTaskLen: 50
  WorkerMode: Bind
  MaxMsgChanLen: 4096
  IOReadBuffSize: 4096
  Mode: websocket
  RouterSlicesMode: true
  LogIsolationLevel: 1
  HeartbeatMax: 10

# my config

#jwtAuth
JwtAuth:
  AccessSecret: ae0536f9-6450-4606-8e13-5a19ed505da0
  AccessExpire: 31536000

DB:
  DataSource: root:PXDN93VRKUm8TeE7@tcp(mysql:3306)/looklook_usercenter?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai

Cache:
  - Host: redis:6379
    Pass: G62m50oigInC30sf
    NonBlock: false
